export { default as Accomodation } from "./Accomodation";
export { default as Accreditations } from "./Accreditations";
export { default as Alias} from "./Alias";
export { default as Area} from "./Area";
export { default as Avatar} from "./Avatar";
export { default as Benefits} from "./Benefits";
export { default as Canonical} from "./Canonical";
export { default as Capacity} from "./Capacity";
export { default as Category} from "./Category";
export { default as Code} from "./Code";
export { default as ContactType } from "./ContactType";
export { default as ContactTypes } from "./ContactTypes";
export { default as Country} from "./Country";
export { default as Course} from "./Course";
export { default as Currencies} from "./Currencies";
export { default as Curriculum} from "./Curriculum";
export { default as Description} from "./Description";
export { default as Designation} from "./Designation";
export { default as Domain } from "./Domain";
export { default as Duration} from "./Duration";
export { default as DurationType} from "./DurationType";
export { default as Email} from "./Email";
export { default as EndDate} from "./EndDate";
export { default as Error } from "./Error";
export { default as EstablishedYear} from "./EstablishedYear";
export { default as EventTicket} from "./EventTicket";
export { default as Facilities} from "./Facilities";
export { default as Facility} from "./Facility";
export { default as Featured} from "./Featured";
export { default as Flag } from "./Flag";
export { default as HostelFees} from "./HostelFees";
export { default as Icon } from "./Icon";
export { default as Id } from "./Id";
export { default as Image } from "./Image";
export { default as Images} from "./Images";
export { default as Intake} from "./Intake";
export { default as Keywords} from "./Keywords";
export { default as Level} from "./Level";
export { default as Link } from "./Link";
export { default as Locale } from "./Locale";
export { default as Location } from "./Location";
export { default as Management} from "./Management";
export { default as Media} from "./Media";
export { default as Name } from "./Name";
export { default as Phone } from "./Phone";
export { default as ProfileId} from "./ProfileId";
export { default as ProfileImage } from "./ProfileImage";
export { default as ProgrammeFees} from "./ProgrammeFees";
export { default as Published } from "./Published";
export { default as Rating} from "./Rating";
export { default as Recommended } from "./Recommended";
export { default as Region} from "./Region";
export { default as Remuneration} from "./Remuneration";
export { default as ShortAddress} from "./ShortAddress";
export { default as Social } from "./Social";
export { default as Specialization} from "./Specialization";
export { default as StaffContacts} from "./StaffContact";
export { default as StartDate} from "./StartDate";
export { default as State} from "./State";
export { default as Status} from "./Status";
export { default as Submit } from "./Submit";
export { default as Thumbnail } from "./Thumbnail";
export { default as Title } from "./Title";
export { default as Types } from "./Type";
export { default as University } from "./University";
export { default as Verified } from "./Verified";
export { default as Verticals } from "./Verticals";
export { default as Views } from "./Views";
export { default as Website } from "./Website";
export { default as ContactName} from "./ContactName"