type Course = {
  id: number;
  courseName: string;
  programmeType: string;
  category: string;
  duration: string;
  seats: number;
  modeOfStudy: string;
  annualFee: number | null;
  fees?: Fee[];
};

type Fee = {
  name: string;
  description: string;
  amount: number;
};

export const coursesData: Course[] = [
  {
    id: 1,
    courseName: "B.Tech in Civil Engineering",
    programmeType: "Undergraduate Programme",
    category: "Engineering",
    duration: "4 Years",
    seats: 100,
    modeOfStudy: "On Campus",
    annualFee: null,
    fees: [
      {
        name: "Partial Scholarship",
        description:
          "75% tuition waiver based on entrance exam scores or academic performance.",
        amount: 15000,
      },
      {
        name: "Installment Payment Plan",
        description:
          "Allows students to pay fees in multiple installments instead of a lump sum.",
        amount: 20000,
      },
      {
        name: "Monthly/Quarterly Installments",
        description: "Payment plans spread across the semester/year.",
        amount: 8000,
      },
      {
        name: "Regular Program Fee",
        description: "Standard tuition for core engineering courses.",
        amount: 60000,
      },
    ],
  },
  {
    id: 2,
    courseName: "B.Tech in Artificial Intelligence",
    programmeType: "Undergraduate Programme",
    category: "Engineering",
    duration: "4 Years",
    seats: 120,
    modeOfStudy: "On Campus",
    annualFee: 70000,
  },
  {
    id: 3,
    courseName: "B.Tech in Aerospace Engineering",
    programmeType: "Undergraduate Programme",
    category: "Engineering",
    duration: "4 Years",
    seats: 80,
    modeOfStudy: "On Campus",
    annualFee: 75000,
  },
  {
    id: 4,
    courseName: "B.Sc in Computer Science",
    programmeType: "Undergraduate Programme",
    category: "Science",
    duration: "3 Years",
    seats: 120,
    modeOfStudy: "On Campus",
    annualFee: 50000,
  },
  {
    id: 5,
    courseName: "M.Tech in Robotics",
    programmeType: "Postgraduate",
    category: "Engineering",
    duration: "2 Years",
    seats: 50,
    modeOfStudy: "On Campus",
    annualFee: 80000,
  },
  {
    id: 6,
    courseName: "M.Sc in Cybersecurity",
    programmeType: "Postgraduate",
    category: "Science",
    duration: "2 Years",
    seats: 60,
    modeOfStudy: "On Campus",
    annualFee: 75000,
  },
  {
    id: 7,
    courseName: "Diploma in Software Engineering",
    programmeType: "Diploma",
    category: "Engineering",
    duration: "2 Years",
    seats: 100,
    modeOfStudy: "Online",
    annualFee: 30000,
  },
  {
    id: 8,
    courseName: "MBA in Technology Management",
    programmeType: "Postgraduate",
    category: "Management",
    duration: "2 Years",
    seats: 70,
    modeOfStudy: "On Campus",
    annualFee: 120000,
  },
  {
    id: 9,
    courseName: "B.Tech in Computer Engineering",
    programmeType: "Undergraduate Programme",
    category: "Engineering",
    duration: "4 Years",
    seats: 90,
    modeOfStudy: "On Campus",
    annualFee: 65000,
  },
  {
    id: 10,
    courseName: "M.Tech in Data Science",
    programmeType: "Postgraduate",
    category: "Engineering",
    duration: "2 Years",
    seats: 45,
    modeOfStudy: "On Campus",
    annualFee: 85000,
  },
  {
    id: 11,
    courseName: "B.Sc in Physics",
    programmeType: "Undergraduate Programme",
    category: "Science",
    duration: "3 Years",
    seats: 80,
    modeOfStudy: "On Campus",
    annualFee: 45000,
  },
  {
    id: 12,
    courseName: "Ph.D in Computer Science",
    programmeType: "Doctorate",
    category: "Science",
    duration: "4 Years",
    seats: 25,
    modeOfStudy: "On Campus",
    annualFee: 90000,
  },
  {
    id: 13,
    courseName: "B.Tech in Electrical Engineering",
    programmeType: "Undergraduate Programme",
    category: "Engineering",
    duration: "4 Years",
    seats: 110,
    modeOfStudy: "On Campus",
    annualFee: 68000,
  },
  {
    id: 14,
    courseName: "M.Sc in Mathematics",
    programmeType: "Postgraduate",
    category: "Science",
    duration: "2 Years",
    seats: 40,
    modeOfStudy: "On Campus",
    annualFee: 55000,
  },
  {
    id: 15,
    courseName: "B.Com in Finance and Accounting",
    programmeType: "Undergraduate Programme",
    category: "Commerce",
    duration: "3 Years",
    seats: 150,
    modeOfStudy: "On Campus",
    annualFee: 40000,
  },
  {
    id: 16,
    courseName: "B.Arch in Architecture and Urban Planning",
    programmeType: "Undergraduate Programme",
    category: "Architecture",
    duration: "5 Years",
    seats: 60,
    modeOfStudy: "On Campus",
    annualFee: 85000,
  },
  {
    id: 17,
    courseName: "M.Phil in Philosophy",
    programmeType: "Postgraduate",
    category: "Humanities",
    duration: "2 Years",
    seats: 30,
    modeOfStudy: "On Campus",
    annualFee: 45000,
  },
  {
    id: 18,
    courseName: "B.A in English Literature",
    programmeType: "Undergraduate Programme",
    category: "Humanities",
    duration: "3 Years",
    seats: 100,
    modeOfStudy: "On Campus",
    annualFee: 35000,
  },
  {
    id: 19,
    courseName: "M.Ed in Education Technology",
    programmeType: "Postgraduate",
    category: "Education",
    duration: "2 Years",
    seats: 45,
    modeOfStudy: "Hybrid",
    annualFee: 50000,
  },
  {
    id: 20,
    courseName: "B.Des in Product Design",
    programmeType: "Undergraduate Programme",
    category: "Design",
    duration: "4 Years",
    seats: 50,
    modeOfStudy: "On Campus",
    annualFee: 75000,
  },
  {
    id: 21,
    courseName: "M.Sc in Biotechnology",
    programmeType: "Postgraduate",
    category: "Science",
    duration: "2 Years",
    seats: 40,
    modeOfStudy: "On Campus",
    annualFee: 80000,
  },
  {
    id: 22,
    courseName:
      "B.Tech in Mechanical Engineering with Specialization in Robotics",
    programmeType: "Undergraduate Programme with Advanced Specialization",
    category: "Engineering",
    duration: "4 Years",
    seats: 75,
    modeOfStudy: "On Campus",
    annualFee: 72000,
  },
  {
    id: 23,
    courseName: "MBA in International Business",
    programmeType: "Postgraduate",
    category: "Management",
    duration: "2 Years",
    seats: 60,
    modeOfStudy: "On Campus",
    annualFee: 110000,
  },
  {
    id: 24,
    courseName: "B.Sc in Data Science",
    programmeType: "Undergraduate Programme",
    category: "Science",
    duration: "3 Years",
    seats: 90,
    modeOfStudy: "Hybrid",
    annualFee: 60000,
  },
];
