name: Sync with Client Private Repository

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Clone Client Repo (Private)
        run: |
          git clone https://${{ secrets.PAT }}@github.com/educrib-platform/educrib-assemble-new.git client-repo
        env:
          MY_PERSONAL_PAT: ${{ secrets.PAT }}

      - name: Merge changes from phase1/DEV
        run: |
          cd client-repo
          git checkout phase1/DEV
          git pull origin phase1/DEV
          cd ..
          
          rsync -av --exclude='.git' client-repo/ .

          git add .
          git commit -m "Merged changes from client repo" || echo "No changes to commit"

          # Use GITHUB_TOKEN for pushing to your public repo
          git remote set-url origin https://github.com/akhil-flycatch/educrib-assemble.git
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

