name: Sync with Client Private Repository

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Clone Client Repo
        run: |
          git clone https://${{ secrets.PAT }}@github.com/educrib-platform/educrib-assemble-new.git client-repo

      - name: Merge changes from phase1/DEV
        run: |
          cd client-repo
          git checkout phase1/DEV
          git pull origin phase1/DEV
          cd ..
          rsync -av --exclude='.git' client-repo/ .
          git add .
          git commit -m "Merged changes from client repo"
          git push origin master
        env:
          PAT: ${{ secrets.MY_PERSONAL_PAT }}

